runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /blog/(signup|login|logout|welcome)
  script: account_control.app
- url: /.*
  script: blog_control.app

libraries:
- name: jinja2
  version: latest
